version: '3.8'

#to run in prod : docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build --force-recreate

services:
  6thmen-nginx:
    image: nginx:alpine
    container_name: 6thmen-admin-nginx
    restart: always
    volumes:
      - .:/var/www:ro,cached
      - ./docker/prod/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_web
    depends_on:
      - 6thmen

  6thmen:
    build: .
    container_name: 6thmen-admin-php
    user: rayuruna:rayuruna
    restart: always
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - 6thmen-db

  6thmen-db:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: 6thmen-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - /var/www/data/6thmen/:/var/lib/postgresql/data:rw
    networks:
      - proxy_db

networks:
  proxy_web:
    name: proxy_web
    external: true
  proxy_db:
    name: proxy_db
    external: true