version: '3.8'

services:
  nginx-admin:
    image: nginx:alpine
    container_name: 6thmen-admin-nginx
    restart: always
    ports:
      - "802:80"
    volumes:
      - ./.:/var/www:ro,cached
      - ./docker/admin/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 6thmen

  6thmen:
    build: .
    container_name: 6thmen-admin-php
    user: rayuruna:rayuruna
    restart: always
    volumes:
      - ./.:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - 6thmen-db

  nginx-api:
    image: nginx:alpine
    container_name: 6thmen-api-nginx
    restart: always
    ports:
      - "803:80"
    volumes:
      - ./.:/var/www:ro,cached
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 6thmen

  6thmen-db:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: 6thmen-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ~/Développement/6thmen-back/docker/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    container_name: 6thmen-adminer
    environment:
      ADMINER_DESIGN: konya
      ADMINER_DEFAULT_SERVER: 6thmen-db
    ports:
      - "8080:8080"
    depends_on:
      - 6thmen-db