version: '3.8'
services:
  phptest:
    image: grafikart/php:php8.2-2
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
    networks:
      - test
    environment:
      DATABASE_URL: postgresql://test:test@dbtest:5432/test?serverVersion=12&charset=utf8
  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    networks:
      - test
  nginx-test-api:
    image: nginx:alpine
    container_name: 6thmen-test-api-nginx
    restart: always
    ports:
      - "803:80"
    volumes:
      - ./.:/var/www:ro,cached
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phptest
    networks:
      - test
  adminer:
    image: adminer
    container_name: 6thmen-test-adminer
    environment:
      ADMINER_DESIGN: konya
      ADMINER_DEFAULT_SERVER: dbtest
    ports:
      - "8080:8080"
    depends_on:
      - dbtest
    networks:
      - test

networks:
  test: