version: '3.8'

services:
  phptest:
    image: grafikart/php:php8.2-2
    volumes:
      - .:/var/www:delegated
    links:
      - dbtest
    networks:
      - test

  dbtest:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    networks:
      - test

  adminer:
    image: adminer
    container_name: 6thmen-test-adminer
    environment:
      ADMINER_DESIGN: konya
      ADMINER_DEFAULT_SERVER: dbtest
    ports:
      - "8080:8080"
    depends_on:
      - dbtest
    networks:
      - test

networks:
  test: