version: '3.8'

#to run in prod : docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build --force-recreate

services:
  nginx-admin:
    image: nginx:alpine
    container_name: 6thmen-admin-nginx
    restart: always
    volumes:
      - ./6thmen-admin:/var/www:ro,cached
      - ./docker/admin/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_web
      - 6thmen-admin
    depends_on:
      - 6thmen-admin

  6thmen-admin:
    build: ./6thmen-admin
    container_name: 6thmen-admin-php
    user: rayuruna:rayuruna
    restart: always
    volumes:
      - ./6thmen-admin:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
    networks:
      - 6thmen-admin
      - 6thmen-db

  nginx-api:
    image: nginx:alpine
    container_name: 6thmen-api-nginx
    restart: always
    volumes:
      - ./6thmen-api:/var/www:ro,cached
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 6thmen-api
    networks:
      - proxy_web
      - 6thmen-api

  6thmen-api:
    build: ./6thmen-api
    container_name: 6thmen-api-php
    user: rayuruna:rayuruna
    restart: always
    volumes:
      - ./6thmen-api:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
    networks:
      - 6thmen-api
      - 6thmen-db

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - /var/www/data/6thmen/:/var/lib/postgresql/data:rw
    networks:
      - 6thmen-admin
      - proxy_db

networks:
  proxy_web:
    name: proxy_web
    external: true
  proxy_db:
    name: proxy_db
    external: true
  6thmen-admin:
    name: 6thmen-admin
  6thmen-api:
    name: 6thmen-api
  6thmen-db:
    name: 6thmen-db
    driver: bridge