<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RsFYLUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rsFYL_u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rsFYL_u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'standing' => ['privates', '.errored..service_locator.rsFYL_u.App\\Entity\\Library\\Standing', NULL, 'Cannot autowire service ".service_locator.rsFYL_u": it needs an instance of "App\\Entity\\Library\\Standing" but this type has been excluded in "config/services.yaml".'],
            'standingRepository' => ['privates', 'App\\Repository\\Library\\StandingRepository', 'getStandingRepositoryService', true],
        ], [
            'standing' => 'App\\Entity\\Library\\Standing',
            'standingRepository' => 'App\\Repository\\Library\\StandingRepository',
        ]);
    }
}
