<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZqDJRgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zq_dJRg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zq_dJRg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.admin' => ['privates', 'debug.security.event_dispatcher.admin', 'getDebug_Security_EventDispatcher_AdminService', false],
            'security.event_dispatcher.api' => ['privates', 'debug.security.event_dispatcher.api', 'getDebug_Security_EventDispatcher_ApiService', false],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.admin' => '?',
            'security.event_dispatcher.api' => '?',
        ]);
    }
}
