<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HfUySl6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HfUySl6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HfUySl6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'season' => ['privates', '.errored..service_locator.HfUySl6.App\\Entity\\Library\\Season', NULL, 'Cannot autowire service ".service_locator.HfUySl6": it needs an instance of "App\\Entity\\Library\\Season" but this type has been excluded in "config/services.yaml".'],
        ], [
            'season' => 'App\\Entity\\Library\\Season',
        ]);
    }
}
