<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VZkf5VqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vZkf5Vq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vZkf5Vq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'teamRepository' => ['privates', 'App\\Repository\\Library\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'teamRepository' => 'App\\Repository\\Library\\TeamRepository',
        ]);
    }
}
