<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Op5yYF2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Op5yYF2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Op5yYF2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sportRepository' => ['privates', 'App\\Repository\\Library\\SportRepository', 'getSportRepositoryService', true],
        ], [
            'sportRepository' => 'App\\Repository\\Library\\SportRepository',
        ]);
    }
}
