<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0yYw7HnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0yYw7Hn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0yYw7Hn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'standing' => ['privates', '.errored..service_locator.0yYw7Hn.App\\Entity\\Library\\Standing', NULL, 'Cannot autowire service ".service_locator.0yYw7Hn": it needs an instance of "App\\Entity\\Library\\Standing" but this type has been excluded in "config/services.yaml".'],
        ], [
            'standing' => 'App\\Entity\\Library\\Standing',
        ]);
    }
}
