<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPkERgSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FPkERgS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FPkERgS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sport' => ['privates', '.errored..service_locator.FPkERgS.App\\Entity\\Library\\Sport', NULL, 'Cannot autowire service ".service_locator.FPkERgS": it needs an instance of "App\\Entity\\Library\\Sport" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sport' => 'App\\Entity\\Library\\Sport',
        ]);
    }
}
