<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IwbEwDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iwb_ewD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iwb_ewD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'team' => ['privates', '.errored..service_locator.iwb_ewD.App\\Entity\\Library\\Team', NULL, 'Cannot autowire service ".service_locator.iwb_ewD": it needs an instance of "App\\Entity\\Library\\Team" but this type has been excluded in "config/services.yaml".'],
            'teamRepository' => ['privates', 'App\\Repository\\Library\\TeamRepository', 'getTeamRepositoryService', true],
        ], [
            'team' => 'App\\Entity\\Library\\Team',
            'teamRepository' => 'App\\Repository\\Library\\TeamRepository',
        ]);
    }
}
