<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateTeamCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateTeamCommand' shared autowired service.
     *
     * @return \App\Command\CreateTeamCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateTeamCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/SluggerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/Slugger/AsciiSlugger.php';

        $container->privates['App\\Command\\CreateTeamCommand'] = $instance = new \App\Command\CreateTeamCommand(($container->privates['App\\Service\\FileManager'] ??= new \App\Service\FileManager()), ($container->privates['slugger'] ??= new \Symfony\Component\String\Slugger\AsciiSlugger('en')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('create:team1');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
