<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePlayerTeamCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreatePlayerTeamCommand' shared autowired service.
     *
     * @return \App\Command\CreatePlayerTeamCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreatePlayerTeamCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileManager.php';

        $container->privates['App\\Command\\CreatePlayerTeamCommand'] = $instance = new \App\Command\CreatePlayerTeamCommand(($container->privates['App\\Service\\FileManager'] ??= new \App\Service\FileManager()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('create:player-team');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
