<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPopulateStandingsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\PopulateStandingsCommand' shared autowired service.
     *
     * @return \App\Command\PopulateStandingsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/PopulateStandingsCommand.php';

        $container->privates['App\\Command\\PopulateStandingsCommand'] = $instance = new \App\Command\PopulateStandingsCommand(($container->privates['App\\Repository\\Library\\TeamRepository'] ?? $container->load('getTeamRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\Library\\LeagueRepository'] ?? $container->load('getLeagueRepositoryService')), ($container->privates['App\\Repository\\Library\\SeasonRepository'] ?? $container->load('getSeasonRepositoryService')));

        $instance->setName('populate:standings');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
