<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPopulateStandingsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\PopulateStandingsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\PopulateStandingsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('populate:standings', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\PopulateStandingsCommand')] fn (): \App\Command\PopulateStandingsCommand => ($container->privates['App\\Command\\PopulateStandingsCommand'] ?? $container->load('getPopulateStandingsCommandService')));
    }
}
