<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSportTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SportType' shared autowired service.
     *
     * @return \App\Form\SportType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SportType.php';

        return $container->privates['App\\Form\\SportType'] = new \App\Form\SportType();
    }
}
