<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_AccessMapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.access_map' shared service.
     *
     * @return \Symfony\Component\Security\Http\AccessMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMapInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/AccessMap.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/ChainRequestMatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcher/PathRequestMatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/RequestMatcher/HostRequestMatcher.php';

        $container->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

        $a = ($container->privates['.security.request_matcher._LA_AHr'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\PathRequestMatcher('^/'));

        $instance->add(new \Symfony\Component\HttpFoundation\ChainRequestMatcher([$a, ($container->privates['.security.request_matcher.95UdEsw'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\HostRequestMatcher('admin.6thmen.com'))]), ['ROLE_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\ChainRequestMatcher([$a, ($container->privates['.security.request_matcher.2JT22x2'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\HostRequestMatcher('api.6thmen.com'))]), ['ROLE_API'], NULL);

        return $instance;
    }
}
