<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m8CGIdN.App\Entity\Library\Sport' shared service.
     *
     * @return \App\Entity\Library\Sport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m8CGIdN": it needs an instance of "App\\Entity\\Library\\Sport" but this type has been excluded in "config/services.yaml".');
    }
}
