<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\TeamController' shared autowired service.
     *
     * @return \App\Controller\Api\TeamController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/TeamController.php';

        $container->services['App\\Controller\\Api\\TeamController'] = $instance = new \App\Controller\Api\TeamController(($container->privates['App\\Repository\\Library\\TeamRepository'] ?? $container->load('getTeamRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\TeamController', $container));

        return $instance;
    }
}
