<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TeamType' shared autowired service.
     *
     * @return \App\Form\TeamType
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Form\\TeamType": argument "$teamRepository" of method "__construct()" has type "App\\Repository\\TeamRepository" but this class was not found.');
    }
}
