<?php

namespace ContainerBfrSDCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YWongQB.App\Entity\Library\Team' shared service.
     *
     * @return \App\Entity\Library\Team
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YWongQB": it needs an instance of "App\\Entity\\Library\\Team" but this type has been excluded in "config/services.yaml".');
    }
}
