<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3nCql5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3nCql5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP3nCql5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP3nCql5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP3nCql5\App_KernelDevDebugContainer([
    'container.build_hash' => 'P3nCql5',
    'container.build_id' => '2de249f0',
    'container.build_time' => 1686909524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP3nCql5');
