<?php

namespace Proxies\__CG__\App\Entity\Library;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Team extends \App\Entity\Library\Team implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'createdIn' => [parent::class, 'createdIn', null],
        "\0".parent::class."\0".'endedIn' => [parent::class, 'endedIn', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'league' => [parent::class, 'league', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'playerTeams' => [parent::class, 'playerTeams', null],
        "\0".parent::class."\0".'sisterTeam' => [parent::class, 'sisterTeam', null],
        "\0".parent::class."\0".'sisterTeams' => [parent::class, 'sisterTeams', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'standings' => [parent::class, 'standings', null],
        "\0".parent::class."\0".'tricode' => [parent::class, 'tricode', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'createdIn' => [parent::class, 'createdIn', null],
        'endedIn' => [parent::class, 'endedIn', null],
        'id' => [parent::class, 'id', null],
        'league' => [parent::class, 'league', null],
        'name' => [parent::class, 'name', null],
        'playerTeams' => [parent::class, 'playerTeams', null],
        'sisterTeam' => [parent::class, 'sisterTeam', null],
        'sisterTeams' => [parent::class, 'sisterTeams', null],
        'slug' => [parent::class, 'slug', null],
        'standings' => [parent::class, 'standings', null],
        'tricode' => [parent::class, 'tricode', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
