<?php

namespace ContainerP3nCql5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLotteryDoneListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LotteryDoneListener' shared autowired service.
     *
     * @return \App\EventListener\LotteryDoneListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/LotteryDoneListener.php';

        return $container->privates['App\\EventListener\\LotteryDoneListener'] = new \App\EventListener\LotteryDoneListener(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
