<?php

namespace ContainerP3nCql5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDraftCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestDraftCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TestDraftCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('testDraft', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\TestDraftCommand')] fn (): \App\Command\TestDraftCommand => ($container->privates['App\\Command\\TestDraftCommand'] ?? $container->load('getTestDraftCommandService')));
    }
}
