<?php

namespace ContainerP3nCql5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDraftCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestDraftCommand' shared autowired service.
     *
     * @return \App\Command\TestDraftCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestDraftCommand.php';

        $container->privates['App\\Command\\TestDraftCommand'] = $instance = new \App\Command\TestDraftCommand(($container->privates['App\\Repository\\TeamRepository'] ?? $container->load('getTeamRepositoryService')));

        $instance->setName('testDraft');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
