<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfrSDCh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfrSDCh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBfrSDCh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBfrSDCh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBfrSDCh\App_KernelDevDebugContainer([
    'container.build_hash' => 'BfrSDCh',
    'container.build_id' => '3e9674c0',
    'container.build_time' => 1688577930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfrSDCh');
